#!/bin/bash

echo "🚀 Quick Setup Commands"
echo "======================="
echo ""
echo "1. Restart dev server:"
echo "   Press Ctrl+C in the terminal, then:"
echo "   npm run dev"
echo ""
echo "2. Seed sample documents:"
echo "   curl -X POST http://localhost:3000/api/seed"
echo ""
echo "3. Open admin panel:"
echo "   open http://localhost:3000/admin"
echo ""
echo "4. Run extraction (click button in admin panel)"
echo ""
echo "5. View playbooks:"
echo "   open http://localhost:3000/playbooks"
echo ""
echo "✅ Using Claude Sonnet 3.5 via OpenRouter!"
